lang: en-US
source: ./nshipster.com
url: http://nshipster.com

title: NSHipster
description: "<strong>NSHipster</strong> is a journal of the overlooked bits in Objective-C and Cocoa. Updated weekly."
permalink: /:title/
lsi: false
markdown: redcarpet
pygments:
  lexer: objective-c

groups:
  - Foundation
  - CoreFoundation
  - CoreGraphics
  - UIKit
  - Objective-C
  - Open Source
  - MapKit
  - Xcode
  - Trivia
  - Miscellanea
