lang: en-US
source: ./nshipster.com
url: http://nshipster.com

title: NSHipster
description: "<strong>NSHipster</strong> is a journal of the overlooked bits in Objective-C, Swift, and Cocoa. Updated weekly."
permalink: /:title/
timezone: America/Los_Angeles

google: 105091289906267717942
issn: 2373-9800

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "disable_indented_code_blocks", "autolink", "strikethrough", "highlight", "superscript", "tables", "footnotes", "with_toc_data"]

highlighter: pygments

groups:
  - Cocoa
  - Objective-C
  - Swift
  - Open Source
  - Xcode
  - Trivia
  - Miscellanea
