lang: zh-Hans
source: ./nshipster.cn
url: http://nshipster.cn

title: NSHipster
description: "<strong>NSHipster</strong> 关注被忽略的 Objective-C、Swift 和 Cocoa 特性。每周更新。"
permalink: /:title/
timezone: Asia/Shanghai
lsi: false

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "disable_indented_code_blocks", "autolink", "strikethrough", "highlight", "superscript", "tables", "footnotes", "with_toc_data"]

highlighter: pygments

groups:
  - Foundation
  - CoreFoundation
  - CoreGraphics
  - UIKit
  - Objective-C
  - Open Source
  - Trivia
  - Miscellanea
